services:
  mongodb:
    image: mongo:5.0
    container_name: mean-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    # ports: # for testing
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      mean-network:

  frontend:
    image: arjf/crud-dd-task-mean-frontend:dev
    container_name: mean-frontend
    restart: always
    depends_on:
      - backend
    # ports: # for testing
    #   - "80:80"
    networks:
      mean-network:

  backend:
    image: arjf/crud-dd-task-mean-backend:dev
    container_name: mean-backend
    restart: always
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}?authSource=admin
      PORT: ${BACKEND_PORT:-8080}
    # ports: # for testing
    #   - "8080:${BACKEND_PORT:-8080}"
    depends_on:
      - mongodb
    networks:
      mean-network:

  # this is decoupled since most likely wont use nginx in prod
  reverse-proxy:
    image: nginx:alpine
    container_name: mean-reverse-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      mean-network:

networks:
  mean-network:
    driver: bridge

volumes:
  mongodb_data:
