name: CD

on:
  workflow_run:
    workflows: ["CI"] # autorun after ci
    types: [completed]
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # debug: true
          port: 22
          envs: MONGO_USER,MONGO_PASS,MONGO_DB
          script: |
            set -e

            if [ ! -d ~/app ]; then
              git clone https://github.com/${{ github.repository }} ~/app
            fi

            cd ~/app
            git pull origin main

            cp .env.example .env || true
            sed -i "s|__MONGO_USER__|$MONGO_USER|g" .env
            sed -i "s|__MONGO_PASS__|$MONGO_PASS|g" .env
            sed -i "s|__MONGO_DB__|$MONGO_DB|g" .env

            docker compose pull
            docker compose up -d --remove-orphans

            docker system prune -f
